

version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8800:8800"
    networks:
      - vactionres-net

  frontend:
    build: ./vactionres-frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - vactionres-net
    depends_on:
      - backend

networks:
  vactionres-net:
    driver: bridge
